task 17/18
PriyankaChaganti/traffic_sign_svm pull request #21
Opened 2019-02-11 12:07 UTC by PriyankaChaganti

no data in hog_Feature folders...hence code imagining data present in folders

2019-02-11 15:24 UTC, sahithi403 requested changes
Download the files. You don't need to imagine about the data

2019-02-11 15:42 UTC, sahithi403 requested changes

2019-02-11 15:42 UTC, sahithi403 commented on robust_svm/process_images.py
> +def get_hog_features(data_set_name,image_file_name):
Lets rename data_set_name to data_class_id so that you don't get confused. Some examples of data_class_id(s) are : 00000, 00013, 00019 folders

2019-02-11 15:42 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog_feature_path = join(data_set_name,image_file_name)
Add a new module settings.py and a variable hog3_feature_path
Set the variable so that it points to HOG3 folder
Import the variable from settings module to this module

2019-02-11 15:42 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog_feature_data = np.concatenate(arrays)
Did you check if numpy is installed in your machine?

2019-02-11 15:42 UTC, sahithi403 commented on robust_svm/process_images.py
> +    data_set_name='../data/training_data/Features_HOG/'
Look at the first comment for examples of data_set_name. In any case, let's rename this to data_class_id

2019-02-11 15:42 UTC, sahithi403 commented on robust_svm/process_images.py
> +    image_file_name = 'HOG_3'
HOG_3 is not an image file name. It is a folder

2019-02-11 17:00 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +    hog_feature_data = np.concatenate(arrays)
yes

2019-02-11 17:14 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +    image_file_name = 'HOG_3'
I have name it 'file' name becoz the parameter is named the same way....

2019-02-11 17:15 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +def get_hog_features(data_set_name,image_file_name):
done

2019-02-11 17:15 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +    hog_feature_path = join(data_set_name,image_file_name)
done

2019-02-11 17:15 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +    data_set_name='../data/training_data/Features_HOG/'
changed

2019-02-11 17:18 UTC, PriyankaChaganti commented
> Download the files. You don't need to imagine about the data

the internet is really slow... I will download the images ASAP

2019-02-12 02:31 UTC, sahithi403 commented on robust_svm/process_images.py
> +    image_file_name = 'HOG_3'
I am not asking you to change the variable name. I am asking you to give proper value to the variable i.e name of any image from Images folder

2019-02-12 02:32 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog_feature_path = join(data_set_name,image_file_name)
What did you change?  I don't see any changes

2019-02-12 02:47 UTC, sahithi403 commented on robust_svm/process_images.py
> +def get_hog_features(data_set_name,image_file_name):
Are you sure that you pushed your commits to the origin?

2019-02-12 13:27 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +    image_file_name = 'HOG_3'
done

2019-02-12 13:28 UTC, PriyankaChaganti commented on robust_svm/process_images.py
> +def get_hog_features(data_set_name,image_file_name):
yes

2019-02-12 15:48 UTC, sahithi403 requested changes

2019-02-12 15:48 UTC, sahithi403 commented on robust_svm/process_images.py
> +def get_hog_features(data_class_id,image_file_name):
An example of an image filename is 00001_00029.ppm 
An example of a data_class_id is 00001
Example of a hog feature file is ' 00001_00029.txt'. This file is present in the path .\data\training\GTSRB_Features_HOG\HOG_03\00000\00001_00029.txt

Assuming that you have created a 'settings.py' module and stored the relative path of hog 3 feature files i.e .\data\training\GTSRB_Features_HOG\HOG_03\

Given just the image filename( 00001_00029.ppm ) and data_class_id(00000), this function is supposed to construct a path that would result in  .\data\training\GTSRB_Features_HOG\HOG_03\00000\00001_00029.txt

2019-02-12 15:48 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog_feature_path = join(data_class_id,image_file_name)
If image filename is 00001_00029.ppm and data_class_id is 00001, hog_feature_path is just 00001/00001_00029.ppm.
That is not the path of the feature file

2019-02-12 15:48 UTC, sahithi403 commented on robust_svm/process_images.py
> +    image_file_name = '00000'
00000 is not an image, it is a folder (data_set_name/ data_class_id)

2019-02-12 15:48 UTC, sahithi403 commented on robust_svm/settings.py
> +hog3_feature_path = "C:/Users/ch.srivamsi priyanka/Documents/GitHub/traffic_sign_svm/data/training_data/Features_HOG/HOG_3"
Use relative path from main.py

2019-02-13 01:13 UTC, PriyankaChaganti commented on robust_svm/settings.py
> +hog3_feature_path = "C:/Users/ch.srivamsi priyanka/Documents/GitHub/traffic_sign_svm/data/training_data/Features_HOG/HOG_3"
the path in main points till Images

2019-02-14 05:53 UTC, sahithi403 requested changes

2019-02-14 05:53 UTC, sahithi403 commented on robust_svm/settings.py
> +hog3_feature_path = "C:/Users/ch.srivamsi priyanka/Documents/GitHub/traffic_sign_svm/data/training_data/Features_HOG/HOG_3"
remove unused imports 

add `project_path = os.path.abspath(__file__ + "/../../")
training_data = "data/training_data"
hog3_path = "Features_HOG/HOG_3"
images_path = "Images"`

above is an example. modify the above variables accordingly


make sure that project_path points to the path of project root folder
make sure that os.path.join(project_path , training_data) points to training_data folder
make sure that os.path.join(project_path , training_data, hog3_path) points to hog3 folder

2019-02-14 05:53 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog3_feature_path = "C:/Users/ch.srivamsi priyanka/Documents/GitHub/traffic_sign_svm/data/training_data/Features_HOG/HOG_3"
import hog3_path from settings

2019-02-14 05:53 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog_feature_path = join(hog3_feature_path,data_class_id,image_feature_filename)
use hog3_path from settings

2019-02-14 05:53 UTC, sahithi403 commented on robust_svm/process_images.py
> +    print(hog_feature_path)
remove prints and unused variables

2019-02-14 05:53 UTC, sahithi403 commented on robust_svm/process_images.py
> +    for image_feature_filename in hog_feature_path:
don't use the for loop. you are reading only one file. you don't need a for loop. use numpy.fromfile to read the feature file

2019-02-15 02:42 UTC, sahithi403 commented on robust_svm/process_images.py
> +    hog_data_array = np.fromfile(hog_feature_path,dtype=float,count=-1,sep=" ")
Overall changes look good

` dtype=float, count=-1, sep=''` These are default values. You don't have to explicitly pass them. No need to change the code now. Just letting you know.

Add the doctsring describing properly what this function does, function params and what it returns. This PR would be good to go

2019-02-15 06:18 UTC, sahithi403 approved these changes

2019-02-15 06:18 UTC, merged